// @ts-nocheck
async function createLuauModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.WorkerGlobalScope,ba="./this.program",ca=import.meta.url,l="",da,ea;if(globalThis.window||aa){try{l=(new URL(".",ca)).href}catch{}aa&&(ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var fa=console.log.bind(console),m=console.error.bind(console),n,p=!1,q;class w{}class y extends w{constructor(a){super();this.ib=a}}var ha,ia,ja=!1;function ka(){var a=z.buffer;B=new Int8Array(a);la=new Int16Array(a);C=new Uint8Array(a);new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);H=new BigInt64Array(a);new BigUint64Array(a)}
function I(a){h.onAbort?.(a);a=`Aborted(${a})`;m(a);p=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ia?.(a);throw a;}var pa;async function qa(a){if(!n)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==pa&&n)a=new Uint8Array(n);else if(ea)a=ea(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function sa(a){var b=pa;if(!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return ra(b,a)}
class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var la,E,H,B,na,oa,F,C,ua=a=>{for(;0<a.length;)a.shift()(h)},va=[],wa=[],xa=()=>{var a=h.preRun.shift();wa.push(a)},J=!0,K=[],L=0,M=null;class N{constructor(a){this.ib=a;this.hb=a-24}}
var za=a=>{var b=M?.ib;if(!b)return O(0),0;var c=new N(b);F[c.hb+16>>2]=b;var d=F[c.hb+4>>2];if(!d)return O(0),b;for(var e of a){if(0===e||e===d)break;if(ya(e,d,c.hb+16))return O(e),b}O(d);return b},Aa=globalThis.TextDecoder&&new TextDecoder,P=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(16<d-b&&a.buffer&&Aa)return Aa.decode(a.subarray(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&63;if(192==(c&224))e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=224==
(c&240)?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;65536>c?e+=String.fromCharCode(c):(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},Ba=0,Ca=[0,31,60,91,121,152,182,213,244,274,305,335],Da=[0,31,59,90,120,151,181,212,243,273,304,334],Q={},Ea=a=>{if(!(a instanceof ta||"unwind"==a))throw a;},Fa=a=>{q=a;J||0<Ba||(h.onExit?.(a),p=!0);throw new ta(a);},Ga=a=>{if(!p)try{a()}catch(b){Ea(b)}finally{if(!(J||0<Ba))try{q=a=q,Fa(a)}catch(b){Ea(b)}}},
R=(a,b,c)=>{var d=C;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Ha={},Ja=()=>{if(!Ia){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Ha)void 0===Ha[b]?delete a[b]:a[b]=Ha[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ia=c}return Ia},Ia,S=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},La=[null,[],[]],Ma=[],T=a=>{var b=Ma[a];b||(Ma[a]=b=Na.get(a));return b},Pa=(a,b,c,d)=>{var e={string:r=>{var u=0;if(null!==r&&void 0!==r&&0!==r){u=S(r)+1;var v=Oa(u);
R(r,v,u);u=v}return u},array:r=>{var u=Oa(r.length);B.set(r,u);return u}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var t=e[c[k]];t?(0===g&&(g=U()),f[k]=t(d[k])):f[k]=d[k]}c=a(...f);return c=function(r){0!==g&&V(g);return"string"===b?r?P(C,r):"":"boolean"===b?!!r:r}(c)};h.noExitRuntime&&(J=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(m=h.printErr);h.wasmBinary&&(n=h.wasmBinary);h.thisProgram&&(ba=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Pa;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Pa(a,b,c,f,d)};
h.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":B[a]=b;break;case "i8":B[a]=b;break;case "i16":la[a>>1]=b;break;case "i32":E[a>>2]=b;break;case "i64":H[a>>3]=BigInt(b);break;case "float":na[a>>2]=b;break;case "double":oa[a>>3]=b;break;case "*":F[a>>2]=b;break;default:I(`invalid type for setValue: ${c}`)}};
h.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return B[a];case "i8":return B[a];case "i16":return la[a>>1];case "i32":return E[a>>2];case "i64":return H[a>>3];case "float":return na[a>>2];case "double":return oa[a>>3];case "*":return F[a>>2];default:I(`invalid type for getValue: ${b}`)}};h.UTF8ToString=(a,b,c)=>a?P(C,a,b,c):"";h.stringToUTF8=(a,b,c)=>R(a,b,c);h.lengthBytesUTF8=S;
var Qa,Ra,W,O,V,Oa,U,Sa,Y,ya,Ta,z,Na,Rb={t:a=>{var b=new N(a);0==B[b.hb+12]&&(B[b.hb+12]=1,L--);B[b.hb+13]=0;K.push(b);return Ta(a)},A:()=>{W(0,0);var a=K.pop();Sa(a.ib);M=null},a:()=>za([]),k:a=>za([a]),y:(a,b)=>za([a,b]),X:()=>{K.length||I("no exception to throw");var a=K.at(-1),b=a.ib;B[a.hb+13]=1;B[a.hb+12]=0;L++;Y(b);M=new y(b);throw M;},aa:a=>{if(a){var b=new N(a);B[b.hb+13]=1;B[b.hb+12]=0;L++;Y(a);M=new y(a);throw M;}},r:(a,b,c)=>{var d=new N(a);F[d.hb+16>>2]=0;F[d.hb+4>>2]=b;F[d.hb+8>>2]=
c;Y(a);M=new y(a);L++;throw M;},ba:()=>L,f:a=>{M||=new y(a);throw M;},P:function(){return 0},na:function(){return 0},oa:function(){},ra:()=>I(""),fa:()=>{J=!1;Ba=0},ha:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getUTCSeconds();E[b+4>>2]=a.getUTCMinutes();E[b+8>>2]=a.getUTCHours();E[b+12>>2]=a.getUTCDate();E[b+16>>2]=a.getUTCMonth();E[b+20>>2]=a.getUTCFullYear()-1900;E[b+24>>2]=a.getUTCDay();E[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0},ia:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=a.getFullYear();E[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Da:Ca)[a.getMonth()]+a.getDate()-1|0;E[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},ga:function(){},Z:(a,b)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!b)return 0;var c=setTimeout(()=>{delete Q[a];Ga(()=>Ra(a,performance.now()))},b);Q[a]={id:c,jb:b};return 0},ja:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(f,e);E[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/
60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(R(a,c,17),R(b,d,17)):(R(a,d,17),R(b,c,17))},xa:function(a){a=a?P(C,a):"";a="function"===typeof h.callJsString?h.callJsString(a):a;a=void 0===a||null===a?"":String(a);var b=S(a)+1,c=Qa(b);R(a,c,b);return c},qa:function(a,b,c){if(!(0<=a&&3>=a))return 28;H[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},pa:()=>Date.now(),da:()=>536870912,ua:()=>performance.now(),ca:a=>{var b=C.length;a>>>=0;if(536870912<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,65536*Math.ceil(Math.max(a,d)/65536))-z.buffer.byteLength+65535)/65536|0;try{z.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},_:(a,b)=>{var c=0,d=0,e;for(e of Ja()){var f=b+c;F[a+d>>2]=f;c+=R(e,f,Infinity)+1;d+=4}return 0},$:(a,b)=>{var c=Ja();F[a>>2]=c.length;a=0;for(var d of c)a+=S(d)+1;F[b>>2]=a;return 0},Ea:a=>{q=a;Fa(a)},O:()=>52,ma:()=>52,ka:function(){return 70},la:(a,
b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=F[b>>2],k=F[b+4>>2];b+=8;for(var t=0;t<k;t++){var r=a,u=C[g+t],v=La[r];0===u||10===u?((1===r?fa:m)(P(v)),v.length=0):v.push(u)}e+=k}F[d>>2]=e;return 0},M:Ua,va:Va,F:Wa,g:Xa,J:Ya,c:Za,h:$a,n:ab,o:bb,p:cb,x:db,s:eb,Ba:fb,I:gb,Aa:hb,Ca:ib,K:jb,T:kb,Y:lb,S:mb,C:nb,za:ob,j:pb,b:qb,ya:rb,d:sb,D:tb,R:ub,Q:vb,sa:wb,z:xb,e:yb,i:zb,m:Ab,l:Bb,q:Cb,u:Db,w:Eb,B:Fb,G:Gb,H:Hb,Da:Ib,W:Jb,V:Kb,E:Lb,L:Mb,ta:Nb,U:Ob,N:Pb,wa:Qb,v:a=>a,ea:Fa};
function sb(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function Za(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function $a(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}function yb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}
function Bb(a,b,c,d,e,f,g){var k=U();try{T(a)(b,c,d,e,f,g)}catch(t){V(k);if(!(t instanceof w))throw t;W(1,0)}}function qb(a,b){var c=U();try{T(a)(b)}catch(d){V(c);if(!(d instanceof w))throw d;W(1,0)}}function Xa(a,b){var c=U();try{return T(a)(b)}catch(d){V(c);if(!(d instanceof w))throw d;W(1,0)}}function Ab(a,b,c,d,e,f){var g=U();try{T(a)(b,c,d,e,f)}catch(k){V(g);if(!(k instanceof w))throw k;W(1,0)}}
function ab(a,b,c,d,e){var f=U();try{return T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}function bb(a,b,c,d,e,f){var g=U();try{return T(a)(b,c,d,e,f)}catch(k){V(g);if(!(k instanceof w))throw k;W(1,0)}}function pb(a){var b=U();try{T(a)()}catch(c){V(b);if(!(c instanceof w))throw c;W(1,0)}}function zb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}
function cb(a,b,c,d,e,f,g){var k=U();try{return T(a)(b,c,d,e,f,g)}catch(t){V(k);if(!(t instanceof w))throw t;W(1,0)}}function Gb(a,b,c,d,e,f,g,k,t,r,u,v){var x=U();try{T(a)(b,c,d,e,f,g,k,t,r,u,v)}catch(A){V(x);if(!(A instanceof w))throw A;W(1,0)}}function Fb(a,b,c,d,e,f,g,k,t,r,u){var v=U();try{T(a)(b,c,d,e,f,g,k,t,r,u)}catch(x){V(v);if(!(x instanceof w))throw x;W(1,0)}}function Lb(a,b,c,d,e,f){var g=U();try{T(a)(b,c,d,e,f)}catch(k){V(g);if(!(k instanceof w))throw k;W(1,0)}}
function Mb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}function db(a,b,c,d,e,f,g,k){var t=U();try{return T(a)(b,c,d,e,f,g,k)}catch(r){V(t);if(!(r instanceof w))throw r;W(1,0)}}function Cb(a,b,c,d,e,f,g,k){var t=U();try{T(a)(b,c,d,e,f,g,k)}catch(r){V(t);if(!(r instanceof w))throw r;W(1,0)}}function jb(a,b,c,d,e,f,g){var k=U();try{return T(a)(b,c,d,e,f,g)}catch(t){V(k);if(!(t instanceof w))throw t;W(1,0)}}
function eb(a,b,c,d,e,f,g,k,t){var r=U();try{return T(a)(b,c,d,e,f,g,k,t)}catch(u){V(r);if(!(u instanceof w))throw u;W(1,0)}}function Db(a,b,c,d,e,f,g,k,t){var r=U();try{T(a)(b,c,d,e,f,g,k,t)}catch(u){V(r);if(!(u instanceof w))throw u;W(1,0)}}function Eb(a,b,c,d,e,f,g,k,t,r){var u=U();try{T(a)(b,c,d,e,f,g,k,t,r)}catch(v){V(u);if(!(v instanceof w))throw v;W(1,0)}}
function Ib(a,b,c,d,e,f,g,k,t,r,u,v,x,A,D,G,ma){var X=U();try{T(a)(b,c,d,e,f,g,k,t,r,u,v,x,A,D,G,ma)}catch(Ka){V(X);if(!(Ka instanceof w))throw Ka;W(1,0)}}function Ua(a){var b=U();try{return T(a)()}catch(c){V(b);if(!(c instanceof w))throw c;W(1,0)}}function nb(a,b){var c=U();try{return T(a)(b)}catch(d){V(c);if(!(d instanceof w))throw d;W(1,0);return 0n}}
function ib(a,b,c,d,e,f,g,k,t,r,u,v,x,A){var D=U();try{return T(a)(b,c,d,e,f,g,k,t,r,u,v,x,A)}catch(G){V(D);if(!(G instanceof w))throw G;W(1,0)}}function fb(a,b,c,d,e,f,g,k,t,r,u){var v=U();try{return T(a)(b,c,d,e,f,g,k,t,r,u)}catch(x){V(v);if(!(x instanceof w))throw x;W(1,0)}}function Jb(a,b,c,d,e,f,g,k,t){var r=U();try{T(a)(b,c,d,e,f,g,k,t)}catch(u){V(r);if(!(u instanceof w))throw u;W(1,0)}}
function Kb(a,b,c,d,e,f,g,k){var t=U();try{T(a)(b,c,d,e,f,g,k)}catch(r){V(t);if(!(r instanceof w))throw r;W(1,0)}}function hb(a,b,c,d,e,f,g,k,t,r,u,v,x){var A=U();try{return T(a)(b,c,d,e,f,g,k,t,r,u,v,x)}catch(D){V(A);if(!(D instanceof w))throw D;W(1,0)}}function Ob(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}function kb(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}
function ob(a,b,c,d,e,f){var g=U();try{return T(a)(b,c,d,e,f)}catch(k){V(g);if(!(k instanceof w))throw k;W(1,0);return 0n}}function Ya(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function xb(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}function Wa(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}
function tb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}function rb(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function Qb(a,b,c){var d=U();try{T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function mb(a,b,c,d){var e=U();try{return T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}function Va(a,b){var c=U();try{return T(a)(b)}catch(d){V(c);if(!(d instanceof w))throw d;W(1,0)}}
function ub(a,b,c,d,e){var f=U();try{T(a)(b,c,d,e)}catch(g){V(f);if(!(g instanceof w))throw g;W(1,0)}}function Nb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}function vb(a,b,c,d){var e=U();try{T(a)(b,c,d)}catch(f){V(e);if(!(f instanceof w))throw f;W(1,0)}}function wb(a,b,c,d,e,f,g){var k=U();try{T(a)(b,c,d,e,f,g)}catch(t){V(k);if(!(t instanceof w))throw t;W(1,0)}}
function Pb(a,b,c,d,e,f){var g=U();try{T(a)(b,c,d,e,f)}catch(k){V(g);if(!(k instanceof w))throw k;W(1,0)}}function lb(a,b,c){var d=U();try{return T(a)(b,c)}catch(e){V(d);if(!(e instanceof w))throw e;W(1,0)}}function gb(a,b,c,d,e,f,g,k,t,r,u,v){var x=U();try{return T(a)(b,c,d,e,f,g,k,t,r,u,v)}catch(A){V(x);if(!(A instanceof w))throw A;W(1,0)}}function Hb(a,b,c,d,e,f,g,k,t,r,u,v,x,A,D,G){var ma=U();try{T(a)(b,c,d,e,f,g,k,t,r,u,v,x,A,D,G)}catch(X){V(ma);if(!(X instanceof w))throw X;W(1,0)}}var Z;
Z=await (async function(){function a(c){c=Z=c.exports;h._call_js_with_string=c.Ha;h._free=c.Ia;h._luau_add_module=c.Ja;h._luau_clear_modules=c.Ka;h._luau_get_modules=c.La;h._luau_execute=c.Ma;h._luau_dump_bytecode=c.Oa;h._luau_set_mode=c.Pa;h._luau_set_solver=c.Qa;h._luau_set_fflags=c.Ra;h._luau_set_source=c.Sa;h._luau_clear_sources=c.Ta;h._luau_get_diagnostics=c.Ua;h._luau_autocomplete=c.Va;h._luau_hover=c.Wa;h._luau_signature_help=c.Xa;Qa=h._malloc=c.Ya;Ra=c.Za;W=c._a;O=c.$a;V=c.ab;Oa=
c.bb;U=c.cb;Sa=c.db;Y=c.eb;ya=c.fb;Ta=c.gb;z=c.Fa;Na=c.Na;ka();return Z}var b={a:Rb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=h.locateFile?h.locateFile?h.locateFile("luau.wasm",l):l+"luau.wasm":(new URL(/* @vite-ignore */ "luau.wasm",import.meta.url)).href;return a((await sa(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!p){ja=!0;Z.Ga();ha?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();va.push(b)}ua(va)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)xa();ua(wa);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ja?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ha=a;ia=b});
;return moduleRtn}export default createLuauModule;
